name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and deploy
      id: builddeploy
      env:
        AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      run: |
        npm install
        npm run build
        npx rimraf ./__sapper__/build
        npx rimraf ./__sapper__/export
        npx rimraf ./public
        npx rimraf ./out
        npx rimraf ./.sapper
        npm run export
        npx rimraf ./__sapper__
        cd __sapper__/export && cp -r * ../../../
        cd ../../..
        npx rimraf ./__sapper__
        npx rimraf .sapper
      env:
        CI: true

    - name: Initialize Azure Static Web Apps
      id: init
      uses: azure/static-web-apps-deploy@v0
      with:
        azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "init"

    - name: Build and Deploy to Azure Static Web Apps
      id: builddeploy
      uses: azure/static-web-apps-deploy@v0
      with:
        azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "deploy"
        app_location: "./dist/packages/client" # App source code path
        output_location: "out" # Build output path
