name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        run: |
          npm install -g pnpm
          pnpm -v # Check PNPM version
        shell: bash

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/client

      - name: Build the Next.js app
        run: pnpm run build-client
        working-directory: ./packages/client

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_STONE_04B27FF1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./dist/packages/client" # Adjust this to match your build output directory
          output_location: 'dist/packages/client'
          app_build_command: 'pnpm run build-client'
