name: Deploy Client Application

on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm install, build
        run: |
          npm install
          npm run build-client

      - name: Check build directory size
        run: du -sh dist/packages/client

      - name: List build directory contents (debugging step)
        run: ls -R dist/packages/client

      - name: Deploy to Azure Static Web Apps
        id: uploaddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_GROUND_0CF65891E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/dist/packages/client/"
          api_location: "" # Api source code path - optional
          output_location: ".next" # Built app content directory - optional
          skip_app_build: true
          skip_api_build: true
