name: Deploy Client Application

on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # timeout-minutes: 30 # Increase the timeout as needed

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: pnpm install, build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build-client

      - name: Check build directory size
        run: du -sh packages/client
        
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_GROUND_0CF65891E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/dist/packages/client"          
          skip_app_build: true
          skip_api_build: true
          apiRuntime: '18'
